# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Home
site_url: https://github.com/fralfaro/r4ds-book
site_author: Francisco Alfaro
site_description: R for data science ( a book with mkdocs )

# Repository
repo_name: hadley/r4ds
repo_url: https://github.com/hadley/r4ds/
edit_uri: ''



# Markdown extensions
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed

# Extra javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Theme
theme:
  name: material
  language: es
  logo: images/logo.bmp
  favicon: images/logo_r.bmp
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hadley
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/hadleywickham/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hadleywickham
    - icon: fontawesome/solid/globe
      link: https://hadley.nz/

# Plugins
plugins:
  - mkdocs-jupyter:
      kernel_name: python3
  - search


# TOC
nav:
    - index.md
    - 01_introduction.ipynb
    - Explore:
        - Introduction: 02_introduction.ipynb
        - 03_ data_visualisation.ipynb
        - 04_workflow_basics.ipynb
        - 05_data_transformation.ipynb
        - 06_workflow_scripts.ipynb
        - 07_exploratory_data_analysis.ipynb
        - 08_workflow_projects.ipynb
    - Wrangle:
        - Introduction: 09_introduction.ipynb
        - 10_tibbles.ipynb
        - 11_data_import.ipynb
        - 12_tidy_data.ipynb
        - 13_relational_data.ipynb
        - 14_strings.ipynb
        - 15_factors.ipynb
        - 16_dates_and _times.ipynb
    - Program:
        - Introduction: 17_introduction.ipynb
        - 18_pipes.ipynb
        - Functions: 19_functions.md
        - 20_vectors.ipynb
        - 21_iteration.ipynb
    - Model:
        - Introduction: 22_introduction.ipynb
        - 23_model_basics.ipynb
        - 24_model_building.ipynb
        - 25_many_models.ipynb
    - Communicate:
        - Introduction: 26_introduction.ipynb
        - 27_r_markdown.ipynb
        - 28_graphics_for_communication.ipynb
        - 29_R_Markdown_formats.ipynb
        - 30_r_markdown_workflow.ipynb



